### ISSUE TITLE
[auto-generated:1956584244] null

### ISSUE THREAD

**Issue by ice1000** [TeamHubApp/intellij-plugin#9]
Raise a bug on Github - Dave

----------------------

- Julia Version: Unknown Julia Version
- Plugin Name: 
- Plugin Version: 
- OS Name: Mac OS X
- Java Version: 1.8.0_152-release
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version name: IntelliJ IDEA
- Is EAP: true
- App Build: IC-183.3975.18
- App Version: 2018.3 EAP
- Last Action: EditorBackSpace
- title: [auto-generated:1956584244] null

```
com.google.firebase.functions.i: Response is not valid JSON object.
	at com.google.firebase.functions.h.onResponse(SourceFile:271)
	at com.b.a.j.b(SourceFile:177)
	at com.b.a.a.d.run(SourceFile:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: c.a.c: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
	at c.a.a.a(SourceFile:112)
	at c.a.d.<init>(SourceFile:157)
	at c.a.d.<init>(SourceFile:170)
	at com.google.firebase.functions.h.onResponse(SourceFile:269)
	... 5 more
```

**Comment by ice1000** [comment]
Angry! Why use my account!
![image](https://user-images.githubusercontent.com/16398479/49167032-9334df00-f302-11e8-9cec-fe8fcb86af4e.png)

I'm gonna invalidate the token soon. Please create your own error reporting account.

**Comment by ice1000** [comment]
Don simply copy my Julia-IntelliJ's error reporter, you should customize it first!

**Comment by RedMillLtd** [comment]
Maybe you can help @ice1000 I want to create the token.bin file with encrypted token.  Can you tell me how to create from github token?

**Comment by ice1000** [comment]
Well there's a main function.

**Comment by RedMillLtd** [comment]
- TeamHub Version: Unknown TeamHub Version
- Plugin Name: TeamHub
- Plugin Version: 0.1.0
- OS Name: Mac OS X
- Java Version: 1.8.0_152-release
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version name: IntelliJ IDEA
- Is EAP: true
- App Build: IC-183.3975.18
- App Version: 2018.3 EAP
- Last Action: 
- title: [auto-generated:1956584244] null
